import { createClient } from "contentful";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MovieCard from "./../components/MovieCard";

export const getStaticProps = async (ctx) => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: "movieName" });

  return {
    props: {
      data: res.items,
      revalidate: 1,
    },
  };
};

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>All favorite movie list here</h1>
      <hr />
      <div className={styles.movieList}>
        {data.map((movie) => {
          return <MovieCard key={movie.sys.id} movie={movie} />;
        })}
      </div>
    </div>
  );
}
